### ISSUE TITLE
Example (Image Blurring) crashes with `LoadError: AssertionError`

### ISSUE THREAD

**Issue by adomasbaliuka** [jakubwro/NumberTheoreticTransforms.jl#1]
The example given in your [documentation](https://jakubwro.github.io/NumberTheoreticTransforms.jl/stable/examples/) crashes on the line `y = ifnt(Y, g, q)` with error message

```
ERROR: LoadError: AssertionError: all((v->begin
            #= /home/alice/.julia/packages/NumberTheoreticTransforms/RMxOE/src/fnt.jl:78 =#
            0 <= v < q
        end), x)
Stacktrace:
 [1] fnt!(x::Vector{Int64}, g::Int64, q::Int64)
   @ NumberTheoreticTransforms ~/.julia/packages/NumberTheoreticTransforms/RMxOE/src/fnt.jl:78
 [2] ifnt!(y::Vector{Int64}, g::Int64, q::Int64)
   @ NumberTheoreticTransforms ~/.julia/packages/NumberTheoreticTransforms/RMxOE/src/fnt.jl:148
 [3] ifnt!(y::Matrix{Int64}, g::Int64, q::Int64)
   @ NumberTheoreticTransforms ~/.julia/packages/NumberTheoreticTransforms/RMxOE/src/fnt.jl:160
 [4] ifnt(y::Matrix{Int64}, g::Int64, q::Int64)
   @ NumberTheoreticTransforms ~/.julia/packages/NumberTheoreticTransforms/RMxOE/src/fnt.jl:180
 [5] top-level scope
   @ ~/<REDACTED>.jl:21
in expression starting at /home/<REDACTED>.jl:21
```

Versions of packages used:

>   [5ae59095] Colors v0.12.8
>   [86fae568] ImageView v0.10.14
>   [916415d5] Images v0.24.1
>   [7475f97c] Mods v1.3.1
>   [8497c1d1] NumberTheoreticTransforms v1.0.0
>   [27ebfcd6] Primes v0.5.0
>   [5e47fb64] TestImages v1.6.2
>   [e462d300] ZernikePolynomials v0.1.0

**Comment by jakubwro** [comment]
Thanks, will have a look

**Comment by jakubwro** [comment]
@adomasbaliuka I fixed the script, but I need to fix docs deployment, what will take me some time. What is your use case for this library?

``` julia
using Images, TestImages, Colors, ImageView
using ZernikePolynomials, NumberTheoreticTransforms

image_float = channelview(testimage("cameraman"))
image = map(x -> x.:i, image_float) .|> Int64

# lens abberation blur model
blur_float = evaluateZernike(LinRange(-41,41,512), [12, 4, 0], [1.0, -1.0, 2.0], index=:OSA)
blur_float ./= (sum(blur_float))
blur = blur_float .|> Normed{UInt8, 8} .|> x -> x.:i .|> Int64
blur = circshift(blur, (256, 256))

# 2D convolution with FNT
t = 4
(g, q) = (314, 2^2^t+1) # g for N = 512 found with scripts/find-ntt.jl
X = fnt(image, g, q)
H = fnt(blur, g, q)
Y = mod.(X .* H, q)
y = ifnt(Y, g, q)
blurred_image = y .>> 8

imshow(image)
imshow(blurred_image)
```

**Comment by adomasbaliuka** [comment]
Thanks for the response!

My use-case is actually probably not relevant for your library. (I want to use NTT to compute (quickly and in NlogN time)the matrix-vector product (mod 2) of a binary Toeplitz matrix with a binary vector. I know how to do it with FFT but it's possible with NTT, which has the advantage of no longer needing to convert back and forth between floating point, as well as having to take care of floating point precision, which can make a difference for very large matrices.

**Comment by jakubwro** [comment]
@adomasbaliuka that is interesting example, my case is similar as I wanted to get rid of floating point errors in the solution. Unfortunately for non trivial problems there is a lot of problems with division by zero in my case. Let me know if NTT approach works for you.

**Comment by adomasbaliuka** [comment]
The online `dev`-docs are not updated by the way (and the online example crashes, although you fixed it in the docs markdown file in the main branch). Shouldn't they be rebuilt (on dev) for every commit? Is it an issue with the CI?

**Comment by jakubwro** [comment]
Yes, I need to migrate CI to github actions
